version: '2'

services:
  jenkins:
    build: ./fs-jenkins
    volumes:
      - ./fs-jenkins/var/run/docker.sock:/var/run/docker.sock
      - ./fs-jenkins/var/jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
    depends_on:
      - gitlab
  gitlab:
    build: ./fs-gitlab
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['omniauth_providers'] = [
          {
            "name" => "github",
            "app_id" => "49ee61869aa2135595a0",
            "app_secret" => "70caeff3023a868d80b80a846ecbccb5d3b040b2",
            "args" => { "scope" => "user:email" }
          }
        ]
    ports:
      - '10080:80'
      - '10022:22'
    volumes:
      - /etc/gitlab
      - /var/log/gitlab
      - /var/opt/gitlab
